dist: trusty
sudo: false
language: python
before_install:
  - export MPLBACKEND='Agg'
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - export MINICONDA_PREFIX="$HOME/miniconda"
  - bash miniconda.sh -b -p $MINICONDA_PREFIX
  - export PATH="$MINICONDA_PREFIX/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a
install:
  #- conda create -q -n test-env --file https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-conda-linux-64.txt
  - wget -q https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py35-linux-conda.yml
  - conda env create -q -n test-env --file qiime2-latest-py35-linux-conda.yml
  #- wget https://data.qiime2.org/distro/core/qiime2-2018.4-py35-linux-conda.yml
  #- travis_retry conda env create -n test-env --file qiime2-2018.4-py35-linux-conda.yml
  #- rm qiime2-2018.4-py35-linux-conda.yml
  - source activate test-env
  - conda install -q nose
  - pip install -q https://github.com/qiime2/q2lint/archive/master.zip
  - pip install -q flake8
  - conda install -c biocore -c bioconda fragment-insertion
  - cp taxonomy_gg99.qza $CONDA_PREFIX/share/fragment-insertion/ref/
  - python setup.py install
script:
  - flake8 setup.py q2_fragment_insertion
  - q2lint
  - qiime dev refresh-cache
  - travis_wait 60 nosetests
